; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port/url, extra scripts
;   Default: board is seeed_xiao_nrf52840
;
; Documentation: http://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_nrf52840]
platform = nordicnrf52
board = seeed_xiao_nrf52840
framework = arduino
board_build.ldscript = nordicnrf52840_s140v7_softdevice.ld

; Enable softdevice S140 for BLE
board_build.softdevice = s140
openocd-interface = cmsis-dap

; Build flags
build_flags =
	-D F_CPU=64000000L
	-I src

; Optimize for size
build_type = release
; build_type = debug

; Monitor settings
monitor_speed = 115200
monitor_filters =
	default

; Adafruit LIS3DH library
lib_deps =
	adafruit/Adafruit LIS3DH
	adafruit/Adafruit Unified Sensor
